In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/multi_touch_attribution_data.csv')

In [ ]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 10000
Columns: 5

In [ ]:
print(df.columns.tolist())

['User ID', 'Timestamp', 'Channel', 'Campaign', 'Conversion']

In [ ]:
df.head()

   User ID            Timestamp         Channel            Campaign Conversion
0    83281  2025-02-10 07:58:51           Email  New Product Launch         No
1    68071  2025-02-10 23:38:48      Search Ads         Winter Sale         No
2    90131  2025-02-11 10:41:07    Social Media     Brand Awareness        Yes
3    71026  2025-02-10 08:19:44  Direct Traffic                   -        Yes
4    94486  2025-02-10 15:15:46           Email         Retargeting        Yes

In [ ]:
df.isnull().sum()

User ID       0
Timestamp     0
Channel       0
Campaign      0
Conversion    0
dtype: int64

In [ ]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [ ]:
print(df.columns.tolist())

['User ID', 'Timestamp', 'Channel', 'Campaign', 'Conversion']

In [ ]:
print("Unique Channels:", df['Channel'].nunique())

Unique Channels: 6

In [ ]:
print("Unique Campaigns:", df['Campaign'].nunique())

Unique Campaigns: 6

In [ ]:
print(df['Channel'].value_counts())

Channel
Direct Traffic    1721
Referral          1685
Display Ads       1669
Social Media      1662
Email             1654
Search Ads        1609
Name: count, dtype: int64

In [ ]:
print(df['Campaign'].value_counts().head())

Campaign
-                     3131
New Product Launch    1416
Retargeting           1379
Brand Awareness       1378
Winter Sale           1372
Name: count, dtype: int64

In [ ]:
print(df['Conversion'].value_counts())

Conversion
No     5056
Yes    4944
Name: count, dtype: int64